// Generated by LiveScript 1.2.0
var Q, pageModel, wrapGenerator, target, COMMENTS_PATTERN, ARGS_PATTERN, ARG_PATTERN, targetFromFn, parseTarget, requestContext, action, inject, toString$ = {}.toString, slice$ = [].slice;
Q = require('q');
pageModel = require('./page-model');
wrapGenerator = require('../harmony/wrap-generator');
target = function(dependencies, targetFn){
  var targetWithContext;
  return targetWithContext = function(ctx){
    var args;
    args = dependencies.map(function(dep){
      var that, err;
      if ((that = ctx[dep]) != null) {
        return that;
      } else {
        err = new Error("Unresolved dependency " + JSON.stringify(String(dep)));
        ({
          meta: {
            targetFn: err[targetFn.name],
            dependencies: err.dependencies,
            dependency: err.dep
          }
        });
        throw err;
      }
    });
    switch (args.length) {
    case 0:
      return targetFn();
    case 1:
      return targetFn(args[0]);
    case 2:
      return targetFn(args[0], args[1]);
    case 3:
      return targetFn(args[0], args[1], args[2]);
    case 4:
      return targetFn(args[0], args[1], args[2], args[3]);
    case 5:
      return targetFn(args[0], args[1], args[2], args[3], args[4]);
    case 6:
      return targetFn(args[0], args[1], args[2], args[3], args[4], args[5]);
    case 7:
      return targetFn(args[0], args[1], args[2], args[3], args[4], args[5], args[6]);
    case 8:
      return targetFn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7]);
    case 9:
      return targetFn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8]);
    case 10:
      return targetFn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8], args[9]);
    default:
      return targetFn.apply(void 8, args);
    }
  };
};
COMMENTS_PATTERN = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg;
ARGS_PATTERN = /^function\s*(\*)?\s*[^\(]*\(\s*([^\)]*)\)/m;
ARG_PATTERN = /^\s*(_?)(\S+?)\1\s*$/;
targetFromFn = function(targetFn){
  var source, ref$, _, genMarker, fnArgs, dependencies;
  source = targetFn.toString().replace(COMMENTS_PATTERN, '');
  ref$ = source.match(ARGS_PATTERN), _ = ref$[0], genMarker = ref$[1], fnArgs = ref$[2];
  dependencies = fnArgs.split(',').map(function(arg){
    return arg.replace(ARG_PATTERN, '$2');
  });
  dependencies = dependencies.filter(function(dep){
    return dep;
  });
  targetFn = wrapGenerator(targetFn);
  return target(dependencies, targetFn);
};
parseTarget = function(rawTarget){
  switch (toString$.call(rawTarget).slice(8, -1)) {
  case 'Function':
    return targetFromFn(rawTarget);
  case 'Array':
    return targetFromArray(rawTarget);
  default:
    throw new Error("Invalid inject target: " + String(rawTarget));
  }
};
requestContext = function(req, params, varargs){
  var app, defaultTemplate, ctx, ref$;
  app = req.app;
  defaultTemplate = req.action === 'index'
    ? req.module
    : req.module + "/" + req.action;
  ctx = (ref$ = {
    req: req,
    params: params,
    varargs: varargs
  }, ref$.controller = app.controller, ref$.config = app.config, ref$);
  if (req.quinnExt != null) {
    import$(ctx, req.quinnExt);
  }
  return Object.defineProperties(ctx, {
    present: {
      value: function(presenter, data){
        return Q.when(data, presenter);
      }
    },
    service: {
      value: function(svcName){
        return app.service(svcName, ctx.req, ctx.i18n);
      }
    },
    page: {
      get: function(){
        var ref$;
        return (ref$ = this._page) != null
          ? ref$
          : this._page = pageModel(req, this.i18n);
      }
    },
    i18n: {
      get: function(){
        if (this._i18n == null) {
          this._i18n = typeof app.localize === 'function' ? app.localize(req) : void 8;
          if (req.module != null) {
            this._i18n.scope = [req.module];
          }
        }
        return this._i18n;
      }
    },
    session: {
      value: req.session
    },
    cookies: {
      value: req.cookies
    },
    config: {
      value: app.config
    },
    render: {
      value: function(tplName, tplCtx, tplOpts){
        var ref$;
        tplName == null && (tplName = defaultTemplate);
        req.__isHtml = true;
        if ('string' !== typeof tplName) {
          ref$ = [tplCtx, tplName, defaultTemplate], tplOpts = ref$[0], tplCtx = ref$[1], tplName = ref$[2];
        }
        tplCtx == null && (tplCtx = ctx.page);
        return app.render(tplName, tplCtx, tplOpts);
      }
    },
    forward: {
      value: function(fwdModuleAction, overrideParams){
        var fwdParams, ref$, fwdModule, fwdAction;
        overrideParams == null && (overrideParams = {});
        fwdParams = {};
        import$(fwdParams, params);
        import$(fwdParams, overrideParams);
        ref$ = fwdModuleAction.split('.'), fwdModule = ref$[0], fwdAction = ref$[1];
        fwdModule || (fwdModule = req.module);
        fwdAction || (fwdAction = 'index');
        return app.executeHandler(req, {
          module: fwdModule,
          action: fwdAction,
          handler: app.controller(fwdModule + "." + fwdAction),
          params: fwdParams
        });
      }
    }
  });
};
action = function(rawTarget){
  var targetWithContext;
  targetWithContext = parseTarget(rawTarget);
  return function(req, params){
    var varargs;
    varargs = slice$.call(arguments, 2);
    return targetWithContext(requestContext(req, params, varargs));
  };
};
module.exports = inject = curry$(function(rawTarget, context){
  return parseTarget(rawTarget)(context);
});
inject.action = action;
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
function curry$(f, bound){
  var context,
  _curry = function(args) {
    return f.length > 1 ? function(){
      var params = args ? args.concat() : [];
      context = bound ? context || this : this;
      return params.push.apply(params, arguments) <
          f.length && arguments.length ?
        _curry.call(context, params) : f.apply(context, params);
    } : f;
  };
  return _curry();
}