// Generated by LiveScript 1.2.0
var i18nHelpers, urlHelpers, pageModel, slice$ = [].slice;
i18nHelpers = function(req){
  return {
    _t: function(key){
      var opts;
      opts = slice$.call(arguments, 1);
      return key;
    }
  };
};
urlHelpers = function(req){
  return {
    route: req.quinnCtx.router.reverseRoute(),
    assetUrl: function(filename){
      return filename;
    }
  };
};
module.exports = pageModel = function(req){
  var page;
  page = {};
  import$(page, urlHelpers(req));
  return import$(page, i18nHelpers(req));
};
pageModel.i18nHelpers = i18nHelpers;
pageModel.urlHelpers = urlHelpers;
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}