// Generated by LiveScript 1.2.0
var objectFromArray, i18nHelpers, urlHelpers, pageModel, slice$ = [].slice;
objectFromArray = function(arr){
  var obj;
  obj = {};
  arr.forEach(function(el, idx){
    if (idx % 2 === 1) {
      return obj[arr[idx - 1]] = el;
    }
  });
  return obj;
};
i18nHelpers = function(i18n){
  return {
    _t: function(key){
      var opts, ref$;
      opts = slice$.call(arguments, 1);
      if (opts.length > 1) {
        opts = objectFromArray(opts);
      } else if (typeof opts[0] === 'object') {
        opts = (ref$ = opts[0]) != null
          ? ref$
          : {};
      } else {
        opts = {};
      }
      return i18n.translate(key, opts);
    }
  };
};
urlHelpers = function(req){
  return {
    route: req.router.reverseRoute(),
    assetUrl: function(filename){
      return filename;
    }
  };
};
module.exports = pageModel = function(req, i18n){
  var page;
  page = {};
  import$(page, urlHelpers(req));
  return import$(page, i18nHelpers(i18n));
};
pageModel.i18nHelpers = i18nHelpers;
pageModel.urlHelpers = urlHelpers;
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}