// Generated by LiveScript 1.2.0
var i18nHelpers, presenter;
i18nHelpers = function(req){
  return {
    translate: function(key){
      return key;
    }
  };
};
module.exports = presenter = function(req){
  return {
    I18n: i18nHelpers(req)
  };
};