// Generated by LiveScript 1.2.0
var clone, byName, TemplateError, statelessSwig;
clone = require('lodash').clone;
byName = function(memo, module){
  memo[module.name] = module;
  return memo;
};
TemplateError = function(error){
  return {
    render: function(){
      return "<pre>" + error.stack + "</pre>";
    }
  };
};
module.exports = statelessSwig = function(modules, config){
  var CACHE, _tags, _filters;
  modules = modules.reduce(byName, {});
  CACHE = {};
  _tags = clone(require('swig/lib/tags'));
  return _filters = clone(require('swig/lib/filters'));
};